### ISSUE TITLE
2nd Recent Commit

### ISSUE THREAD

**Issue by cQuirarte** [chrisngobanh/welp#11]
I don't know what the hell happened. The first was intended, the second was a little confusing. I did "git pull origin master" before I began to add changes. Then I did this: 

Carloss-MacBook-Air:welp Freedom$ git add --all
Carloss-MacBook-Air:welp Freedom$ git commit -m "Question on Review Menu Design"
[master f77e754] Question on Review Menu Design
 1 file changed, 17 insertions(+), 20 deletions(-)
Carloss-MacBook-Air:welp Freedom$ git push origin master
To git@github.com:chrisngobanh/welp.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:chrisngobanh/welp.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by cQuirarte** [comment]
Sorry if I messed something up.

**Comment by banhathome** [comment]
Git is telling you that there are changes on GitHub that you do not have. To fix this, you just need to run `git pull origin master`

This happened because someone pushed commits after your last pull

**Comment by cQuirarte** [comment]
I also wrote some questions on the first commit, where it shows green.  If anybody can answer and let me know how you want me to design the review menu, that'd be great.
